### ISSUE TITLE
Request failed with status code 422

### ISSUE THREAD

**Issue by ryanpcmcquen** [CompuIves/codesandbox-client#926] opened 2018-06-25 18:13 UTC
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I am trying to load and hack on my repo (https://github.com/SurLaTable/slt-ui/tree/feature/fix-codesandbox) using CodeSandbox.

### Your Environment
| Browser: Chrome |

I get a 422 error ... I am not sure why. This only happens with branches that have a `/` in them.

**Comment by ryanpcmcquen** [comment] 2018-06-28 15:02
@CompuIves, any ideas on this?

**Comment by ryanpcmcquen** [comment] 2018-06-29 18:36
Is there a way to have CodeSandbox point to a specific entry point?

**Comment by CompuIves** [comment] 2018-06-30 22:49
Hey! I can't open the GitHub repository, could that be the reason that CodeSandbox has trouble importing it?

**Comment by ryanpcmcquen** [comment] 2018-07-01 04:45
I am no longer able to reproduce this (even with the old commit that I was using). Is there a way for CodeSandbox to read some `package.json` attribute that points to custom `index.js` only intended for CodeSandbox?

**Comment by ryanpcmcquen** [comment] 2018-07-02 16:04
@CompuIves, I am getting the error again, it must have to do with the slash in the branch name:
https://codesandbox.io/s/github/SurLaTable/slt-ui/tree/feature/fix-codesandbox

**Comment by ryanpcmcquen** [comment] 2018-07-18 21:38
@CompuIves, it is definitely the slash in the branch name. Can we improve branch parsing to escape the slashes? I was digging around for the parser but couldn't find it.

**Comment by CompuIves** [comment] 2018-07-18 22:55
Yep, that definitely could be it. We need a better way to detect the branch, we do that here currently:

https://github.com/codesandbox-app/codesandbox-importers/blob/master/packages/git-extractor/src/index.ts#L35

**Comment by ryanpcmcquen** [comment] 2018-07-18 23:20
I don't see an example of escaping `/` in the `koa-router` docs, so I created an issue there:

https://github.com/alexmingoia/koa-router/issues/469

**Comment by bobziroll** [comment] 2018-11-02 16:08
@CompuIves I'm also receiving this error, but it only happens when I try to submit a PR via CodeSandbox. No slash in the URL for this one. Only happens for some repos, e.g.:

[Student 1's toy project](https://github.com/Hamaerox/assignments/tree/master/assignments/projects/Mario)
[Student 2's toy project](https://github.com/Tyler-Palmer/assignments/tree/master/exercises/business-time)

**Comment by bobziroll** [comment] 2018-11-07 20:39
The CSB links in my above comment won't work anymore because we were able to get the PR functionality to work, but now it seems very spotty (most of the time it fails with a 422 error again). I haven't been able to figure out what steps make it work. I'll probably open my own issue for this.

**Comment by JustinTBrown** [comment] 2018-11-21 08:16
I am receiving 422s when exporting to GitHub as well.

**Comment by bobziroll** [comment] 2018-11-30 22:38
Update: it seems like any repository that contains a React app (bootstrapped with create-react-app) seems to have no issues at all with the PR feature. On the other hand, static websites seem to have the highest likelihood of getting the 422 error. I'll update this message if I find out more info that might help diagnose the problem.

**Comment by CompuIves** [comment] 2018-12-03 11:24
Hey @bobziroll, I can't seem to access the sandbox you linked here. Is it private perhaps?

**Comment by bobziroll** [comment] 2018-12-05 22:54
@CompuIves Shoot, I've since deleted it because I was testing out steps to fixing it. Sorry!

Relating to testing what causes this - I seriously can't figure out any consistent pattern that causes the 422 error when trying to create the PR. I ran through the following steps:

1. Have 2 computers side-by-side, each logged in to a different Github account
2. Import a sandbox from a Github url (both computers importing the same code)
3. Fork the sandbox, make a trivial change somewhere, and save the file
4. Open the Github menu on the left, fill in the fields, and attempt to submit the PR.

On one of the attempts, both computers worked in creating a PR. On another attempt, one computer worked while another didn't. On the computer that didn't work, I logged out of their sandbox and github and logged into mine, then tried again and it worked fine. Then, (thinking it had something to do with my Github account and wanting to test that theory), I logged out of my Github/sandbox accounts and back into _their_ accounts (assuming it wouldn't work and my theory would be validated), but this time the PR creation worked just fine! So I'm back to having 0 working theories as to what is causing the 422 error.

**Comment by reflash** [comment] 2019-01-24 08:07
Same problem. I have a React App and once I try to export it to GitHub repo I get 422 error

**Comment by subtleGradient** [comment] 2019-03-03 11:21
Same problem here.
Here's my sandbox: https://codesandbox.io/s/km0p41o9jo

**Comment by simplywondrous** [comment] 2019-03-18 18:37
I got the same error - it seems to occur when you try to create a Github Repo when you already have one with the same name.

For a while I'd make a sandbox, export it to Github, then when redirected, be confused as to why the sidebar no longer showed and try to re-access the sandbox from my account dashboard... where the Github tab would ask to Create Repository and I'd try to make the repo again only to encounter an error as there would already be a repo named the same name under my account (created when I exported it the first time).

Steps:
1. Create a new React Sandbox and save (sandbox will be forked, and be something like "https://codesandbox.io/s/r53x69n3zm")
2. Export to GitHub - name it REPO_NAME, and click Create Repository
3. Repo will be created, and page redirects to "https://codesandbox.io/s/github/{USERNAME}/{REPO_NAME}/tree/master/". Left Sidebar (Project Info, File Editor, etc) will not be shown.
5. If you now go back to your account dashboard and access that same repo again(r53x69n3zm), the Github sidebar tab will ask you once again to Create Repository, and if you use the same REPO_NAME a 422 error will result.

Solution:
The solution for me was realizing I needed to save once I was at "https://codesandbox.io/s/github/{USERNAME}/{REPO_NAME}/tree/master/", and that would fork it and give me yet another new sandbox - "https://codesandbox.io/s/zn51vz9kkm". This new repo would then be connected to the Github repo.

**Comment by lbogdan** [comment] 2019-03-21 19:38
Hey @ryanpcmcquen , is this still an issue?

If so, can you please provide a sandbox / github link experiencing this? (all the ones I tried from the OP and comment don't seem to work anymore)

If not, can you please close it? Thanks!

**Comment by ryanpcmcquen** [comment] 2019-03-21 20:49
@lbogdan, here is one: https://codesandbox.io/s/github/SurLaTable/slt-ui/tree/bugfix/storeselector-doc-fix

Which now gives a module limit issue.

**Comment by lbogdan** [comment] 2019-03-22 08:31
That's a legitimate error, caused by out current limit of 250 modules (files, really) per sandbox.

**Closed** 2019-03-22 22:51 UTC
Labels: Github Integration

**Comment by haroldao** [comment] 2019-12-14 15:12
> Same problem here.
> Here's my sandbox: https://codesandbox.io/s/km0p41o9jo

How did you fix your issue?

**Comment by Jen-Pearson** [comment] 2020-05-05 07:33
I know this is an old looking thread but I had this when trying to create React_TicTacToe.  By removing the _ to make it ReactTicTacToe. It completed without the 422 code error.  Nothing obvious in the browser - just got that processing image forever until I opened dev tools to find out what was going on :) 

On the github side of things I can now see a repo called React-tictactoe.  Weird!

**Comment by jineeshjohn** [comment] 2022-07-07 15:00
Try this link [https://github.com/codesandbox/codesandbox-client/issues/6556#issuecomment-1078777593](url) fixed for me.
