### ISSUE TITLE
Anchors in React do not fire onClick handlers if a hash is present in the link

### ISSUE THREAD

**Issue by tannerlinsley** [CompuIves/codesandbox-client#1462] opened 2019-01-11 23:34 UTC
# 🐛 bug report

## Description of the problem
When a hash is placed in the link of an anchor element in React, the onClick handler for the component doesn't fire. This only happens in the preview though. If you open the standalone window of the app, you'll see it works just fine.

###  Link to sandbox: [link](codesandbox.io/s/4w20jlxz0)

Possible Related Issues: #1226

**Comment by SaraVieira** [comment] 2019-02-20 09:33
Im gonna close this one as it's a duplicate of https://github.com/CompuIves/codesandbox-client/issues/1463

We will check it there

**Closed by SaraVieira** 2019-02-20 09:33 UTC
