### ISSUE TITLE
File Upload "Entity Too Big"

### ISSUE THREAD

**Issue by colshacol** [CompuIves/codesandbox-client#759] opened 2018-04-25 18:24 UTC
Just wondering about upload filesize limits after this tweet by the all mighty @CompuIves last night.

https://twitter.com/CompuIves/status/988899843656568833

I've confirmed that the filesize limit is larger than the 1mb that I originally thought, but I have tested and found that I can not upload a 4.2mb file, although a 3.9mb file works just fine. I have tested these files with both drag and drop as well as the "upload selection" feature. (I don't know what to call the normal way of uploading files...)

I am assuming that there are variables at play when uploading a file that can... cause the final size to be different? >.> I don't know. I'm not very good with technology. 🤷‍♂️ 

<img width="370" alt="screen shot 2018-04-25 at 1 11 47 pm" src="https://user-images.githubusercontent.com/19484365/39264826-6763a3c4-488b-11e8-9b9f-ced86790b253.png">

**Comment by lbogdan** [comment] 2018-04-28 16:35
The limit in nginx is 5MB (`client_max_body_size 5M;`), but considering files are transferred in base64, the maximum file size can be anywhere between 4-5MB, depending on its contents.

Now, about the errors (cc @CompuIves ):
* we should have a descriptive error, something like `File too large, upload file size limit is 5MB`, probably returned from https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/store/providers/Api.js#L20, as the 413 response is returned by nginx directly and doesn't even reach the API;
* also, there are two error notifications, one caused by the API error handler https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/store/providers/Api.js#L58, and the second one by the store action: https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/store/modules/files/actions.js#L138 -> https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/store/modules/files/sequences.js#L108.

I have a (hackish) PR that fixes those, I'll upload it shortly and let's move the discussion there.

**Comment by lbogdan** [comment] 2018-04-28 17:09
You can test it here http://pr766.cs.lbogdan.tk/s/new by forking and trying to upload a file larger than 5MB. The error notification should look like this:
![](https://bogdanl.tinytake.com/media/75461f?filename=1524935206675_28-04-2018-08-06-42.png&sub_type=thumbnail_preview&type=attachment&width=422&height=103)

**Closed** 2018-04-29 16:41 UTC
Labels: PR opened
