### ISSUE TITLE
Links not working in embedded browser

### ISSUE THREAD

**Issue by nikolasburk** [CompuIves/codesandbox-client#1479] opened 2019-01-18 15:53 UTC
# 🐛 bug report

When the embedded browser renders HTML that contains a link (i.e. an `<a>` tag), it is not possible to open that link with a "normal" click.

It currently just opens a blank page. Adding `target="_blank"` also doesn't help.

**Comment by lbogdan** [comment] 2019-01-18 15:55
Hey @nikolasburk , can you please provide a sandbox manifesting this behavior?

**Comment by nikolasburk** [comment] 2019-01-18 16:02
This one for example: https://codesandbox.io/s/k948plrnk5

The rendered HTML that includes an `<a>` tag is located inside `src/helpers/info.ts`. Note that in my embedded browser it currently still renders an old version of the HTML with the `<a>` tag (is this a caching issue or am I missing something?):

![image](https://user-images.githubusercontent.com/4058327/51398009-cc3f4200-1b42-11e9-8938-acef89754f18.png)

**Comment by lbogdan** [comment] 2019-01-18 16:18
If it's a caching issues, it's most probably express related. Did you try to restart the sandbox?

**Comment by SaraVieira** [comment] 2019-01-18 17:08
Hey Nik!

If you fork it does work the problem is indeed cache but at the moment we are building a force reboot button because the only way to fix it in FE is to frok the sandbox and it restarts everything

About your second one I see it fine

@lbogdan correct me if i am saying something dumb

**Comment by lbogdan** [comment] 2019-01-18 17:10
@nikolasburk If you own the sandbox, you have a "Restart Sandbox" button in the "Server" panel:
![image](https://user-images.githubusercontent.com/2083930/51401911-b0449c00-1b54-11e9-938e-992f27aa8afb.png)

**Comment by lbogdan** [comment] 2019-01-18 17:12
@SaraVieira That's only for github imported sandboxes, as they have no owner, but they get automatically restarted when the repo is updated, so it's all fine. 🙂

**Comment by nikolasburk** [comment] 2019-01-22 08:47
Thanks a lot for your input! 🙌  I think this was some sort of a caching issue, in any case, this CSB now has a minimal reproduction of my issue: https://codesandbox.io/s/5zv95r2j9l

It renders this simple HTML:

```html
<div>
  <div>👉 Follow the instructions <a href="http://bit.ly/setup-prisma-client-demo-ts">here</a></div>
</div>
```

This is the render output:

![image](https://user-images.githubusercontent.com/4058327/51522854-9f34ad00-1e2a-11e9-9120-0f2640ded68d.png)

However, when clicking the link nothing happens.

**Comment by lbogdan** [comment] 2019-01-22 08:54
Looking at the console errors, it's most probably because of
![image](https://user-images.githubusercontent.com/2083930/51523281-0440d080-1e34-11e9-83ab-e2b7b506b6c7.png)

**Comment by lbogdan** [comment] 2019-03-22 21:22
It looks like `http` was the culprit here, I have a fixed version here: https://codesandbox.io/s/xor879jz1o . I used `target="_blank"`, otherwise you get `Refused to display 'https://github.com/prisma-csb/prisma-client-demo-ts/blob/master/SETUP.md' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".` , which makes sense because the preview is inside an iframe.

Closing this, feel free to reopen if you have further issues.

**Closed by lbogdan** 2019-03-22 21:22 UTC
