### ISSUE TITLE
Allow to add multiple dependencies at once

### ISSUE THREAD

**Issue by FezVrasta** [CompuIves/codesandbox-client#1626] opened 2019-03-20 13:33 UTC
# 🌈 Feature

Right now, to add 2 or more dependencies, you have to manually open the "add new dependency" panel once for each dependency. It'd be great if codesandbox allowed to add them all with a single command, maybe separating them with a comma.

**Comment by lbogdan** [comment] 2019-03-22 16:34
Closing this as duplicate of #565 .

**Closed by lbogdan** 2019-03-22 16:34 UTC
Labels: enhancement
