### ISSUE TITLE
CodeMirrow auto-scrolling on input

### ISSUE THREAD

**Issue by pavloDeshko** [CompuIves/codesandbox-client#573] opened 2018-02-20 17:39 UTC
another problem with CodeMirror - on input editor scrolls itself to the line of input (puts this line to the very bottom of the viewport)
Provided there are more lines above than editor's height, of course
Firefox 58

**Comment by CompuIves** [comment] 2018-02-21 14:54
Hey! I think this is intended behaviour, right?

So if I understand correctly, if your cursor is not in view and you start typing, it scrolls to the cursor?

**Comment by pavloDeshko** [comment] 2018-02-21 15:24
nope, it jumps to cursor anyway, whether out of view or in 
![jump](https://user-images.githubusercontent.com/27104046/36488389-ffdb6f60-172b-11e8-9c4d-e53d7c49138c.gif)

**Comment by bitblitter** [comment] 2018-03-01 12:33
Same thing happening in Chrome 64.0.3282.186
If it's intended, could there be an option to disable this behaviour?

**Comment by SaraVieira** [comment] 2019-03-20 16:59
Issue closed as we dropped the CodeMirror editor in the latest release

**Closed by SaraVieira** 2019-03-20 16:59 UTC
