### ISSUE TITLE
Started today - cyrillic text uses a different font now

### ISSUE THREAD

**Issue by CodeSpartan** [CompuIves/codesandbox-client#1621] opened 2019-03-19 21:42 UTC
# 🐛 bug report

Platform: Windows, two different machines and browsers (Chrome and Firefox)
Here's how cyrillic text used to look, the same font as english:
![vue](https://user-images.githubusercontent.com/10173914/54643689-2e171c00-4aa0-11e9-9067-967d6ec66e30.png)

Now it looks like this:
![new](https://user-images.githubusercontent.com/10173914/54643812-7b938900-4aa0-11e9-8fa6-f8eebcf945c6.png)

**Comment by SaraVieira** [comment] 2019-03-20 20:52
Hey!

Can you tell me what font you are using and also can you send an example sandbox ?

**Comment by CodeSpartan** [comment] 2019-03-20 22:08
Hi,

I can reproduce this on a brand new Parcel sandbox, Vue also. Using the default font & theme.

**Comment by SaraVieira** [comment] 2019-03-21 13:06
Hey!

The issue is that we changed the fallback font and the default one that is Dank Mono doesn't support  Greek, Hebrew, and Cyrillic so a quick fix for this would be to remove dank mono from the font family input here:
<img width="702" alt="Screenshot 2019-03-21 at 14 04 54" src="https://user-images.githubusercontent.com/1051509/54753898-7b030b80-4be2-11e9-80ed-af2142ba7d09.png">

**Comment by lbogdan** [comment] 2019-03-21 17:03
Can't reproduce on Windows 10, latest Chrome, using `Menlo, "Source Code Pro", monospace` font family:

![image](https://user-images.githubusercontent.com/2083930/54770456-edd4ac80-4c0b-11e9-97a0-79e086de2b0a.png)

**Comment by lbogdan** [comment] 2019-03-21 17:13
@CodeSpartan If you like and still want to use Dank Mono, you could set your font family to `dm, monospace`, which, while not perfect, I think it looks a bit better:

![image](https://user-images.githubusercontent.com/2083930/54771183-65efa200-4c0d-11e9-95f7-0048c4dbde49.png)

**Comment by CodeSpartan** [comment] 2019-03-25 15:01
Yes, it looks much better with `dm, monospace`, thanks!

**Comment by lbogdan** [comment] 2019-03-25 15:16
Nice! Closing this, as I think there's nothing more we can do here.

**Closed** 2019-03-25 15:17 UTC
Labels: need more info, workaround
