### ISSUE TITLE
Code in terminal not updating

### ISSUE THREAD

**Issue by marcosc90** [CompuIves/codesandbox-client#1641] opened 2019-03-21 19:46 UTC
# 🐛 bug report

## Description of the problem

When I update the code on the editor, the code on the terminal is not updated. When creating CLI applications, it's almost impossible to work, because most of the time the changes are not synced correctly.

Is there a way to sync?

![image](https://i.imgur.com/qvDbV62.png)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553195562-ec6c48980
| Browser | 72.0.3626.109 
| Operating System | Ubuntu 18.04

**Comment by CompuIves** [comment] 2019-03-21 19:48
That's indeed weird, it should sync automatically. Does your console in the devtools say anything weird?

**Comment by lbogdan** [comment] 2019-03-21 19:50
Hey @marcosc90 , thanks for your bug report!

This might (or might not) be related to #1455 . Either way, this is clearly not supposed to happen.

**Comment by marcosc90** [comment] 2019-03-21 19:56
> That's indeed weird, it should sync automatically. Does your console in the devtools say anything weird?

Nothing weird, just a few errors when the page loads, but nothing else. No errors at all when saving, and even after refreshing the page, the file is completely saved, but the terminal is not updating correctly.

> Hey @marcosc90 , thanks for your bug report!
> 
> This might (or might not) be related to #1455 (see [my comment](https://github.com/CompuIves/codesandbox-client/issues/1455#issuecomment-475351965) ). Either way, this is clearly not supposed to happen.

You're welcome. I don't know if it's related to that, don't think so, but I do have that issue too, and it doesn't bother me right now. My issue affects me directly since I'm unable to use the platform for CLI scripts.

**Comment by marcosc90** [comment] 2019-03-21 20:12
It's probably related, but `nodemon` stopped working. The server is not restarting anymore.

**Comment by lbogdan** [comment] 2019-03-28 17:35
Hey @marcosc90 ,

I can't really replicate this, has it been happening since? If so, do you have a consistent way to trigger it?

**Comment by marcosc90** [comment] 2019-03-28 17:41
It has happened again, but I don't have a consistent way of triggering it. Once the sandbox is is initialized again, everything is synced.

So as a workaround, maybe a button to reinitialize the Sandbox can be added, or just a button to force sync.

I'll update if I find a way to trigger it.

**Comment by lbogdan** [comment] 2019-03-28 17:44
Yeah, we will add a button that allows restarting the whole container (instead of just the devserver) soon-ish!

Please buzz me as soon as this happens again if possible, it would be nice to be able to debug it live. Thanks!

**Comment by marcosc90** [comment] 2019-04-04 22:38
> Please buzz me as soon as this happens again, if possible; it would be nice to be able to debug it live. Thanks!

@lbogdan It's happening right now, if you give me a way to contact you privately, I can give you the link of the sandbox (It's an unlisted one)

**Comment by lbogdan** [comment] 2019-04-05 08:27
@marcosc90 Sorry, I was asleep when you commented, we're probably in quite different time zones. For next time, I'm `luca.bogdan` on Skype.

**Comment by lbogdan** [comment] 2019-04-08 09:16
Closing this, as I'm pretty sure it's been resolved by #1729 . @marcosc90 feel free to reopen if it's still happening for you.

**Closed by lbogdan** 2019-04-08 09:16 UTC
Labels: ASAP, SSE, bug, need more info

**Comment by lbogdan** [comment] 2019-04-08 10:37
@marcosc90 One more thing: before the sync issue happening, did you by any chance get a notification saying "10 updates in less than 2 seconds, disabling file synchronization"?

**Comment by bumpewto** [comment] 2019-04-25 18:02
Hi @lbogdan I have the same sync issue as @marcosc90 with the "10 updates..." notification.

So I managed to reproduce the issue in minimal conditions, and got hit with the notification as soon as I tried to install packages in a subdirectory. From there on, nothing in the editor got updated the via command line.
Here's the link for the sandbox, [https://zqlko706ol.sse.codesandbox.io/](https://zqlko706ol.sse.codesandbox.io/)

Hope this comment is useful for you !

**Comment by lbogdan** [comment] 2019-04-25 18:11
@bumpewto That's because, for now, we don't support syncing that many files. We honor `.gitignore`, though (only the one in the sandbox's root folder), so what you'll probably want to do is to put whatever you don't want to sync (like `node_modules`) in there, e.g.:
```
#.gitignore
front/node_modules
workspace/node_modules
# or just "node_modules" which will globally ignore all module folders
```

**Comment by bumpewto** [comment] 2019-04-25 18:26
Alright that's crystal clear, thank you for your quick answer !

**Comment by Lathryx** [comment] 2021-05-04 19:10
I've been having the same exact issue with files not syncing! I've seen that there's a limit, and I did get the `10 updates in less than 2 seconds, disabling file synchronization` error message. I wasn't too far into my new project so instead, I decided to just restart with a new container sandbox since I hadn't found any answers. I had the same problem, even before installing any dependencies! 

In my first attempt ([sandbox #1](https://codesandbox.io/s/react-express-app-not-working-ifkm6)), I had run `npx create-react-app client`, and this is when I got the error message/notification in the bottom righthand corner. I was able to see everything in the terminal window, but I'm not going to do React development through *Vim*. My other problem was seeing the files synchronized in other sandboxes with the same thing, like [this one](https://codesandbox.io/s/example-create-react-app-express-forked-lecme?file=/client/src/App.js). Moving on, during my second attempt ([sandbox #2](https://codesandbox.io/s/react-express-app-z225y?file=/package.json)), all I had done is start a new `Node HTTP Server` sandbox (which is what I had used beforehand with [sandbox #1](https://codesandbox.io/s/react-express-app-not-working-ifkm6)), delete the `src` directory, and run `npm init`. The changes can be seen in the terminal window, but the files are still not synced, even in a completely new container sandbox! 

I really enjoy using CSB for my React development! However, this is hindering my ability to do so. What should I do? 
***Note:*** *I also noticed that, in [sandbox #1](https://codesandbox.io/s/react-express-app-not-working-ifkm6), after running `npx create-react-app client`, the `package.json` inside of `./client/src/` seemed to be missing things like its dependency array, scripts (the one currently there was added by me), etc. Not sure if this is related or not, but worth mentioning! Any reason for this?*

**Comment by rayfoss** [comment] 2021-07-13 13:50
I encountered this problem in the Vue 3 templates. Nodemon is installed on a parent container and will run with yarn, ignoring what's on your package.json. To good news is it will respect .gitignore, AFTER a server restart.

This .gitignore managed to not trip the limiter on a `vue create` run.
```
node_modules/
.codesandbox/

```
