### ISSUE TITLE
Exception when importing from github

### ISSUE THREAD

**Issue by mweststrate** [CompuIves/codesandbox-client#205] opened 2017-09-25 15:00 UTC
When going to this url: 

https://codesandbox.io/s/github/mweststrate/react-next-2017-demo

I get his exception:

```
An error occured when fetching the sandbox:

Cannot convert undefined or null to object
```

**Comment by CompuIves** [comment] 2017-09-25 15:49
Ah, I know the cause of this error. Expect a fix this evening! It's because
devDependencies or dependencies is undefined.

Thanks for reporting it☺️

**Comment by CompuIves** [comment] 2017-09-25 15:54
Decided to tick off deployment from Schiphol from my bucketlist. Should be fixed now! (https://github.com/CompuIves/codesandbox-git-extractor/commit/56f48f0fbf417b0c2a1011b853347783c9900f3e)

**Closed by CompuIves** 2017-09-25 15:54 UTC
