### ISSUE TITLE
Use React-Show for sidebar

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#358] opened 2017-12-03 16:04 UTC
The sidebar has multiple sections (WorkshopItem) that can be expanded and collapsed. This happens without any animation. I just found out about https://github.com/react-tools/React-Show and I think it would be interesting if we'd use this to animate the collapsing/expanding.

**Comment by j13l** [comment] 2017-12-03 18:22
React-Show looks neat, I'd give this a shot.

By WorkshopItem you mean WorkspaceItem, right? And the requirements are to animate opening/closing the Project, Files & Dependencies tabs with React-Show. Correct?

I'm a first-time contributor, so could you please provide an outline of what you expect to be done?Shall I write tests? I don't see any inside the pages folder.

Thanks!

**Comment by CompuIves** [comment] 2017-12-03 18:32
That's great @j13l!! Very much appreciated 😄 .

> By WorkshopItem you mean WorkspaceItem, right? 

Yep, I don't know what I was thinking when I wrote WorkshopItem haha.

> And the requirements are to animate opening/closing the Project, Files & Dependencies tabs with React-Show. Correct?

Exactly.

>  so could you please provide an outline of what you expect to be done?Shall I write tests? I don't see any inside the pages folder.

There are no tests needed for this functionality. We have a PR pipeline for code styling, we generally follow Prettier which is automated. The main requirement is the animation of collapsing/expanding those sections, like you mentioned 🙂 .

Also, if you have any quick questions or need help, you can contact me directly via Discord (mentioned in `README.md`).

**Comment by j13l** [comment] 2017-12-03 18:38
Alright, sounds simple enough 🙂
I'm on it and also joined Discord for any follow-up questions.

Thanks!

**Comment by j13l** [comment] 2017-12-03 20:59
Seems like there's an issue with ReactShow & nested components. The parent's height does not get updated when a child expands. This is the case when we open a directory inside the Files Workspace.

Opened up an issue here https://github.com/react-tools/react-show/issues/2, including a Codesandbox example to reproduce it. 

Couldn't find any quick workaround yet. 🙁

**Comment by pfftdammitchris** [comment] 2017-12-03 22:22
I think this would be a great feature. Maybe providing some settings option in the settings to disable/configure the speed based on user preferences. I feel like users who are suffering from laggy animations due to some cpu resourceful operation happening in their background processes might want to turn it off somehow.

**Comment by tannerlinsley** [comment] 2017-12-04 17:35
By the way guys, I'll have the option for width animation as well next week. Stay tuned!

**Closed** 2017-12-11 13:13 UTC
Labels: beginner friendly, enhancement, help wanted
