### ISSUE TITLE
classProperties support

### ISSUE THREAD

**Issue by murtraja** [CompuIves/codesandbox-client#1299] opened 2018-11-14 11:44 UTC
# ❔ What needs to be done in order to enable classProperty support

/node_modules/react-native-confirmation-code-input/components/ConfirmationCodeInput.js: Support for the experimental syntax 'classProperties' isn't currently enabled (10:20):

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1541799550-1e6ec17
| Browser | firefox
| Operating System | ubuntu

**Comment by Infi-Knight** [comment] 2018-11-19 09:40
Try adding the plugin in your .babelrc
 ```js
"plugins": [
"@babel/plugin-proposal-class-properties"
]
```
It might be the case that .babelrc is being ignored in which case you can try creating a babel.config.js and setting up babel config there.

**Comment by murtraja** [comment] 2018-11-22 03:39
@Infi-Knight , Thank you for your response. I have updated the [sandbox](https://codesandbox.io/s/14jr1kq7q7). Added entries in babelrc + have a babel config + have an override for the particular project which is causing problems. Unfortunately, the error persists. One thing I could try is simply copy-paste the contents of the project into src and then try if the error is still there.

**Comment by lbogdan** [comment] 2019-03-26 21:07
Closing this, as `create-react-app` template not supporting `classProperties` is expected behavior. Also, it looks like you solved it in the meanwhile, so kudos! 🙂

**Closed by lbogdan** 2019-03-26 21:07 UTC

**Comment by drout0** [comment] 2022-08-10 18:08
cool, you closed it. Care to write as the final post "what" was done to solve the issue? (without us having to sift thru comments to find that out) -- that's what would differ from sifting thru browser's result pages, after all ...
