### ISSUE TITLE
Add sandbox configuration to change default opened file

### ISSUE THREAD

**Issue by EisenbergEffect** [CompuIves/codesandbox-client#1254] opened 2018-10-31 04:53 UTC
# 🌈 Feature

When building out sandboxes for Aurelia, we have to include a custom loader to enable Aurelia to integrate with the codesandbox loader/bundler. This file is not needed in a real Aurelia project at all. However, it's needed for the sandbox to function. To get everything working, we have to set this file to the package's main. As a result, an Aurelia sandbox always opens up to this special codesandbox file, rather than to the interesting code files that the sandbox focuses on. We'd like the ability to specify, in the sandbox configuration, which file should open by default when a sandbox loads. Ideally, we'd like for people to not even see this special file, but we'd be happy to just be able to specify the default file as something other than what's in the package.json main.

For reference, here's a sandbox that exhibits the problem: https://codesandbox.io/s/jznoxqrw73 We'd much rather display our `main` or `app` files. We never want the `codesandbox` file to display.

**Comment by CompuIves** [comment] 2018-10-31 16:53
This is so interesting!

I agree with the feature request, it's a really good one, but wouldn't it also make sense to have an Aurelia template that handles this logic?

I think we could introduce a new template that has the `initialize();` in `preset.setup` and maybe a custom transpiler to inject the configure logic?

**Comment by EisenbergEffect** [comment] 2018-10-31 23:34
We would certainly love to have a custom template. There's another issue somewhere related to that and some work @bigopon was doing to try to put it together. I think it was a bit difficult figuring out the best way to put it all together. @bigopon can provide a few more details and the issue link.

**Comment by lbogdan** [comment] 2019-03-26 21:24
Closing this, as it was fixed with the adding of the Aurelia template. It's also a duplicate of #514 , you can track progress there if still interested in this feature.

**Closed by lbogdan** 2019-03-26 21:24 UTC
