### ISSUE TITLE
🐛 New File Duplication when using VSCode UI Experiment

### ISSUE THREAD

**Issue by Saeris** [CompuIves/codesandbox-client#1380] opened 2018-12-13 20:49 UTC
Filling this issue as requested by @lbogdan after discussing it in Discord.

When you use the file explorer UI to create a new file within a sandbox, that file and it's nested folder structure is duplicated in that part of the UI once the file has been given a name. This only seems to happen when the VSCode experiment is turned on, and the file explorer UI will go back to normal if you refresh the page. To be clear, this doesn't seem to be creating duplicate files, only that the UI displays a duplicate. Please refer to the following screenshot for an example:

![duplicate files screenshot](https://cdn.discordapp.com/attachments/386515307922980865/522536461875281921/unknown.png)

I haven't confirmed if this is specific to container sandboxes, but that is where the issue occurred for me. So as far as reproduction steps go:

1. Create a new Node container sandbox
2. Enable VSCode experiment in preferences
3. Click the create new file icon in the file explorer UI inside the sandbox
4. Give your file a name, hit enter, and watch as the file and folder structure are duplicated
5. Added bonus: create some nested folders and watch as the folders get recursively duplicated as well
6. Refresh the page and take note that the UI now appears as expected again

While I don't have a recording, I did show the issue happening in a screenshare with Luca. Until a solution is found, the issue can be worked around by disabling the VSCode experiment.

**Comment by brennowilliam** [comment] 2018-12-18 19:08
I'm looking to make a contribution to code sandbox. 

Do you guys think it would be a good first issue for me to work on?

**Comment by SharanSMenon** [comment] 2019-03-11 01:13
Yea

**Comment by lbogdan** [comment] 2019-03-22 11:46
(although this was opened first) Closing it as a duplicate of https://github.com/CompuIves/codesandbox-client/issues/1455 .

**Closed by lbogdan** 2019-03-22 11:46 UTC
Labels: bug
