### ISSUE TITLE
Support Resize of Editor Panel on iPad

### ISSUE THREAD

**Issue by rbiggs** [CompuIves/codesandbox-client#1291] opened 2018-11-09 14:36 UTC
# 🌈 Feature

Allow user to resize the Editor Panel using touch on iPad. Currently it is possible to resize the tree view on the left side while on iPad. But this only affects the size of the Tree Panel. The result is that the editing area is small and cramped on iPad with no way to increase its size through touch and drag. 

User should be able to touch and drag from either side of the Editor Panel to increase its size.

Since touch and drag already work with the Tree Panel, I'm sure it's just a matter of doing the same thing for the Editor Panel. Maybe the support is there, but due to CSS issues on iPad the draggable handle is not exposed???

**Comment by KenzoBenzo** [comment] 2018-12-10 07:56
+1

**Comment by tzhelyazkova** [comment] 2019-03-16 22:36
@rbiggs @KenzoBenzo can you please provide a video recording of the issue? I can't reproduce it on iPad Pro using Safari.

**Comment by lbogdan** [comment] 2019-03-22 15:53
Closing this, as I'm pretty sure it was solved by the recent switch to VSCode as the default editor. Feel free to reopen if you still have issues.

**Closed by lbogdan** 2019-03-22 15:53 UTC
Labels: bug, ui
