### ISSUE TITLE
public/ folder and using stylesheets

### ISSUE THREAD

**Issue by vvo** [CompuIves/codesandbox-client#460] opened 2018-01-17 09:11 UTC
Hey hi, I am trying to inject a stylesheet on https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/InstantSearch.js.

It seems to be using create-react-app by default so inside public/index.html I put:

```html
<link rel="stylesheet" href="%PUBLIC_URL%/search.css">
```

And I have a `public/search.css` file, but it's not loading. Hints?

**Comment by vvo** [comment] 2018-01-17 09:18
Workaround: just put style.css in src/ and do `import './style.css';` it works by default.

But still there might be a bug so leaving opened here

**Comment by CompuIves** [comment] 2018-02-19 15:20
Haha, I just found the problem. It looks like we have our own styles.css there as well. Found out by testing it in this sandbox: https://codesandbox.io/s/yjm821kq91.

I'll fix this by removing the styles.css, it was for our old homepage.

**Comment by CompuIves** [comment] 2018-04-07 11:55
Should be fixed with this commit: https://github.com/CompuIves/codesandbox-client/commit/07f16383d73d23442acaa8a349a9da346b1d23c9

**Comment by CompuIves** [comment] 2018-04-07 18:04
Confirmed to be fixed!

**Closed by CompuIves** 2018-04-07 18:04 UTC
