### ISSUE TITLE
Cannot find path: @babel/runtime-corejs2/helpers/interopRequireWildcard

### ISSUE THREAD

**Issue by kimmohakkarainen** [CompuIves/codesandbox-client#1143] opened 2018-10-02 16:00 UTC
# 🐛 bug report

Today react-bootstrap sandbox lost parts of babel-functionality. It seems that at the same time there was updates to newer babel-version. 

I am building a simple application on top of react & bootstrap. Importing certain components from "react-bootstrap" causes error message:
Cannot find path: @babel/runtime-corejs2/helpers/interopRequireWildcard

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Google Chrome Version 69.0.3497.100 | 
| Windows 10 |

**Comment by colshacol** [comment] 2018-10-02 16:16
This is related to #1142, as well.

I woke this morning to one of my sandboxes displaying "Cannot find path: @babel/runtime/helpers/builtin/classCallCheck" or something similar.

https://codesandbox.io/s/m9v813r23x

And upon going to another sandbox, I get issues with "Support for the experimental syntax 'decorators-legacy' isn't currently enabled (6:3)"

https://codesandbox.io/s/v666o17963

Neither of these issues existed yesterday.

**Comment by CompuIves** [comment] 2018-10-02 17:04
Pushed a fix

**Comment by CompuIves** [comment] 2018-10-02 17:05
Should be out within 10min!

**Comment by CompuIves** [comment] 2018-10-02 17:20
Build crashed with out of memory, ETA 10 min!

**Comment by CompuIves** [comment] 2018-10-02 17:20
https://circleci.com/gh/CompuIves/codesandbox-client/12274

**Comment by CompuIves** [comment] 2018-10-02 17:44
The initial issue is fixed. Should be out in another 10 min.

> Support for the experimental syntax 'decorators-legacy' isn't currently enabled (6:3)

This one is a bit more tricky because CRA v2 doesn't support decorators I believe. The easiest fix would be to downgrade react-scripts to 1.0.3 for the time being. Maybe I'm wrong though, would love to know!

**Comment by colshacol** [comment] 2018-10-02 17:55
Confirmed, react-scripts 1.1.5 fixes decorators. :+1:

**Comment by colshacol** [comment] 2018-10-02 17:55
All seems to be fine now, as far as I see. Many thanks for your haste, good sir!

**Comment by kimmohakkarainen** [comment] 2018-10-02 17:59
Works again! Many thanks on my behalf too :-)

**Comment by CompuIves** [comment] 2018-10-02 18:00
Closing as the initial issue is fixed, we can open another one for the decorators issue if that one is supported by CRA v2.

**Comment by CompuIves** [comment] 2018-10-02 18:01
Oops

**Closed by CompuIves** 2018-10-02 18:01 UTC
