### ISSUE TITLE
Facebook share codesanbox.io warning

### ISSUE THREAD

**Issue by calpa** [CompuIves/codesandbox-client#1297] opened 2018-11-13 00:53 UTC
# ❔ Question

I don't know why but it happens when I share link of codesandbox in facebook...
```
It looks like this link is unsecure: codesandbox.io

To protect your account, we recommend not posting the link. If you want to share it anyway, you'll need to complete this security check.
```

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome
| Operating System | MacOS

**Comment by lbogdan** [comment] 2019-03-26 21:15
Closing this, as I can't reproduce it, and it was most probably just a temporary Facebook fluke.
![image](https://user-images.githubusercontent.com/2083930/55033892-d7b85900-501c-11e9-8757-80c51d4d0b9e.png)

@calpa If that still happens for you, feel free to reopen, and also provide us with the sandbox for which it happens.

**Closed by lbogdan** 2019-03-26 21:15 UTC
