### ISSUE TITLE
require.context is not a function

### ISSUE THREAD

**Issue by michaeltintiuc** [CompuIves/codesandbox-client#1482] opened 2019-01-21 11:11 UTC
When importing a project from github which is working, I am getting a `reqiure.context is not a function` error

Link:
https://codesandbox.io/s/7zz3x644nx

Running on:
Linux, Firefox, Chrome

**Comment by michaeltintiuc** [comment] 2019-02-05 11:49
Even though the original issue is still there, I have opted into changing the code of the library and not using webpack specific imports, still there is an issue with deployment:

https://codesandbox.io/s/github/ModusCreateOrg/ionic-vue-examples/

`_ionicons.addIcons` however it does work locally, and the compiled `main.js` file looks not quite the same as the original one:

Original:

```js
// Ionic core styles and theming
import '@ionic/core/css/core.css'
import '@ionic/core/css/ionic.bundle.css'

// Import IonVuePage component
import IonVuePage from '@/components/IonVuePage.vue'

import { addIcons } from 'ionicons'
// Enable the ionic-vue plugin
Vue.use(Ionic)
```

Compiled:

```js
// Ionic core styles and theming
// Import IonVuePage component
// Enable the ionic-vue plugin
_vue.default.use(_ionicVue.default); // Register as global component to be used as boilerplate
_vue.default.component('IonVuePage', _IonVuePage.default); // Create a new Vue instance
```

Code is missing and only comments are left.

**Comment by lbogdan** [comment] 2019-03-22 18:30
Closing this as duplicate of #723 .

**Closed by lbogdan** 2019-03-22 18:30 UTC
