### ISSUE TITLE
React App Template: HTML <head> tags in <body>

### ISSUE THREAD

**Issue by bbeaumatin** [CompuIves/codesandbox-client#556] opened 2018-02-15 10:49 UTC
Hello,

When I create a new React App, all the `<head>` tags get duplicated in the `<body>`.
The file is correct when received by the browser (see network tab in chrome devtools), but the browser puts `<head>` tags in the `<body>` when interpreted (that or a CSB related script is causing this effect).

It doesn't really prevent me to use codesandbox but it has a few drawbacks, for example if I put a `<link>` tag to an external CSS and i use webpack css loader into the app, the external CSS will take priority on imported CSS because the `<link>` tab gets copied into the `<body>` (and then get positioned in the DOM after the imported CSS that webpack puts into the `<head>`).

Browser: Chrome up-to-date (v63)

It also happens when i import a project into codesandbox and that problem didn't occur on my local environment.

Tell me if you need more details to help you tackle this issue.

**Comment by CompuIves** [comment] 2018-02-19 14:21
Good one! I know how to fix this one, but need to find a way to fix this without breaking local dev environment for the contributors.

**Comment by lbogdan** [comment] 2018-05-03 00:33
@bbeaumatin Are you still having this issue? I can't seem to reproduce it.
@CompuIves Was this fixed?

**Comment by CompuIves** [comment] 2018-05-03 01:44
This (https://github.com/CompuIves/codesandbox-client/pull/702) will fix it, I can finish that PR soonish.

**Comment by bbeaumatin** [comment] 2018-05-04 06:15
@lbogdan Yes the issue is still here, if you try to create a new React app, open the preview in a new window and inspect the DOM with Chrome Dev Tools for exemple, and you can see <head> markup in <body>.

@CompuIves Thanks for solving this soonish 👍 

Btw great quality tool overall i'm using it very often and i'm always enjoying it, the live session feature is amazing. It has become my tool of choice for prototyping, demoing, starting new apps. Thanks!

**Comment by the0neWhoKnocks** [comment] 2018-05-12 18:53
@CompuIves Any traction on your PR? Looks like the last commit was Apr 7, but there are `test-integrations` errors on the PR.

@lbogdan It's definitely still an issue. Currently I'm adding ids to link tags so I can clean them out of the body.

**Comment by CompuIves** [comment] 2018-05-20 20:14
Fixed in master, will be deployed either this evening or tomorrow morning.

**Closed** 2018-05-20 20:13 UTC
Labels: bug
