### ISSUE TITLE
Jest does not work as described in the docs

### ISSUE THREAD

**Issue by hiredgunhouse** [CompuIves/codesandbox-client#1357] opened 2018-12-06 16:53 UTC
The docs here https://codesandbox.io/docs/tests state that adding Jest and files that match specific patterns will make test work.
Here's an example that shows it does not work: https://codesandbox.io/s/w7knyzxl75
I'm guessing that in order to use Jest you need to use the React template because an example at the bottom of the docs page I referred to does exactly that, but the docs don't state that one has to use the React template. It seems that adding Jest as a dependency should also work.

**Comment by lbogdan** [comment] 2019-03-26 20:33
Is this a docs issue only? I ask because the sandbox you provided currently errors with `jest.doMock is not a function`.

**Comment by SaraVieira** [comment] 2019-04-02 09:39
Hey!

I am gonna close as this does not seem to be a Doc issue but a jest one because we don't yet support mocking and in that case it's a duplicate of https://github.com/CompuIves/codesandbox-client/issues/692 and some others

Thank you!

Feel free to reopen if you think opposite

**Closed by SaraVieira** 2019-04-02 09:39 UTC
Labels: docs, jest, need more info

**Comment by hiredgunhouse** [comment] 2019-04-08 14:46
Yes, the tests run fine as long as I don't try to use mocking.
