### ISSUE TITLE
How to run backend + frontend?

### ISSUE THREAD

**Issue by Automedon** [CompuIves/codesandbox-client#1519] opened 2019-02-04 02:15 UTC
Here is a question how I can setup for example create-react-app+express. When here i cant chose port in the browser window? And the terminal is not availabale.

**Comment by Haroenv** [comment] 2019-02-11 14:33
<img width="909" alt="screenshot 2019-02-11 at 15 32 41" src="https://user-images.githubusercontent.com/6270048/52569835-590faf80-2e12-11e9-9d9e-783b0e1a08c4.png">

For a server, you'd choose the "node" template. However, to also have React available; the easiest would be to use the "next" template.

**Comment by Automedon** [comment] 2019-02-12 00:09
and then How I supposed to send require from front to back?

**Comment by SaraVieira** [comment] 2019-02-20 09:30
This is for now not really possible unless you just display an HTML page from express :(

I'm gonna close as it's a duplicate of https://github.com/CompuIves/codesandbox-client/issues/1519

**Closed by SaraVieira** 2019-02-20 09:30 UTC

**Comment by hacknlove** [comment] 2019-10-23 11:11
> I'm gonna close as it's a duplicate of #1519

This is #1519, so maybe you mix up the issue number.

¿Could you indicate which issue should I look for?
