### ISSUE TITLE
.gitignore not work when export to github

### ISSUE THREAD

**Issue by greatMonster11** [CompuIves/codesandbox-client#1409] opened 2018-12-26 13:17 UTC
# 🐛 bug report
After I finished my project. I want to export my project to github by using extension on code sandbox, the left bar. I've added gitignore file and put my env variable to prevent pushing it. 

But it didn't work. the file still uploaded on github without stoped by gitignore file.

Here is my project: https://codesandbox.io/s/q9nl8z4rlq

Plz help me. If i say something wrong plz correct me. Thanks

**Comment by SaraVieira** [comment] 2019-01-04 19:36
Hey!

The link you provided does not exist :(

Can you get us a new sandbox link?

**Comment by simplywondrous** [comment] 2019-03-18 19:00
This seems to be the same issue as https://github.com/CompuIves/codesandbox-client/issues/323.

**Comment by lbogdan** [comment] 2019-03-21 19:29
Closing this as duplicate of #323 .

**Closed by lbogdan** 2019-03-21 19:29 UTC
