### ISSUE TITLE
Codesandbox not colour editing

### ISSUE THREAD

**Issue by bau123** [CompuIves/codesandbox-client#1000] opened 2018-07-23 09:32 UTC
Since last week, codesandbox editor has lost its colour scheme and is now only in black and white. What has happened?

**Comment by CompuIves** [comment] 2018-07-23 13:02
Heya! Which browser are you on? We recently changed our tokenizer to use WebAssembly to tokenize so that could be the cause. I thought that the majority of our browsers support it, I can change our behaviour to have a fallback though.

**Comment by bau123** [comment] 2018-07-23 13:17
Hi,
I'm using Microsoft Edge 38.14393.2068.0.

**Comment by lbogdan** [comment] 2019-03-28 17:20
Closing this, as I can't reproduce, and I'm quite confident that it it was actually a bug, it has been fixed since. However, @bau123 feel free to reopen if it's still happening for you.

**Closed by lbogdan** 2019-03-28 17:20 UTC

**Comment by didi2391** [comment] 2019-09-11 09:35
![image](https://user-images.githubusercontent.com/24479458/64685810-36776f00-d4a5-11e9-89fd-c2cdfe44a18f.png)

I am facing the same issue(editor is showing only black and white) with codesandbox on all the browsers

Attached picture for references

Do I have to change some settings in the sandbox though to fix this issue ? Tried everything but no luck
