### ISSUE TITLE
Regression with React

### ISSUE THREAD

**Issue by oliviertassinari** [CompuIves/codesandbox-client#1741] opened 2019-04-06 13:10 UTC
# 🐛 bug report

## Description of the problem

For some reason, codesandbox fails to run with React. It used to work.

###  Link to sandbox

https://codesandbox.io/s/ykrxxomqlj

**Comment by SaraVieira** [comment] 2019-04-06 13:16
Hey!

This is because our bundler changed its directory searching and to maximize compatibility with Create React App it's searching for the index.html file inside the public folder and you don't have one:

I moved it to that folder and it seems to work now

https://codesandbox.io/s/jnwpokv8m3

Sorry about the issues and let me know if that fixes it for you

**Comment by oliviertassinari** [comment] 2019-04-06 13:20
@SaraVieira Should I change the Material-UI integration?

**Comment by SaraVieira** [comment] 2019-04-06 13:52
I'm not sure we do, the best person to handle with the bundler may be @compuives 

Ping ping

**Comment by CompuIves** [comment] 2019-04-06 14:07
I committed a fix for this, I'll add a test case for this as well. Sorry for the regression!

**Closed** 2019-04-06 14:06 UTC

**Comment by oliviertassinari** [comment] 2019-04-06 14:08
@CompuIves thanks ✨

**Comment by CompuIves** [comment] 2019-04-06 14:27
It's lvie!

**Comment by oliviertassinari** [comment] 2019-04-06 14:33
It works.
