### ISSUE TITLE
With a circular dependency, `TypeError: Cannot redefine property` from the bundler

### ISSUE THREAD

**Issue by sompylasar** [CompuIves/codesandbox-client#705] opened 2018-04-07 21:12 UTC
https://codesandbox.io/s/61zjk5n05k?module=%2Fsrc%2Findex.js

```
TypeError: Cannot redefine property: a
    at Function.defineProperty (<anonymous>)
    at evaluate (https://61zjk5n05k.codesandbox.io/src/index.js:9:8)
    at r.a (https://codesandbox.io/static/js/sandbox.37512735.js:5359:971)
    at e.value (https://codesandbox.io/static/js/sandbox.37512735.js:5418:270)
    at https://codesandbox.io/static/js/sandbox.37512735.js:5391:22872
    at Array.forEach (<anonymous>)
    at e.value (https://codesandbox.io/static/js/sandbox.37512735.js:5391:22843)
    at https://codesandbox.io/static/js/sandbox.37512735.js:3877:8157
    at t (https://codesandbox.io/static/js/common-sandbox.a360099a.js:1937:811)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.a360099a.js:1937:599)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.a360099a.js:1937:990)
    at n (https://codesandbox.io/static/js/common-sandbox.a360099a.js:2110:316)
    at https://codesandbox.io/static/js/common-sandbox.a360099a.js:2110:412
```

<img width="1440" alt="screen shot 2018-04-07 at 2 10 05 pm" src="https://user-images.githubusercontent.com/498274/38460388-95187eec-3a6d-11e8-9146-c7e6f10d5710.png">

**Comment by CompuIves** [comment] 2018-04-07 22:46
Interesting, I'm getting a different error: (0 , _.a) is not a function.
Which is intended behavior I think since on initial run a should export {}.

I'm on a phone right now, but I can debug further tomorrow!

**Comment by sompylasar** [comment] 2018-04-08 00:51
Yes, I expected `a` to be `undefined`, this sandbox is supposed to illustrate circular dependency issue, but stumbled upon this when I finished the code on desktop.

I'm on mobile (Android Chrome) now, too, and this sandbox is stuck on the loading screen.
![screenshot_20180407-174246](https://user-images.githubusercontent.com/498274/38461724-49cf2f20-3a8c-11e8-8522-b578340d3201.png)

**Comment by CompuIves** [comment] 2018-04-08 17:59
Hm weird, this is what I'm getting:

![screen shot 2018-04-08 at 19 58 19](https://user-images.githubusercontent.com/587016/38470717-41fcfd32-3b67-11e8-8484-479494a6b73d.png)

The earlier redefine error is certainly possible. We do Hot Module Replacement when you make changes, so in that case `a.js` could already have been evaluated before `b.js` was created. A full refresh should still give the `a is undefined` error though.

**Comment by lbogdan** [comment] 2019-03-28 16:14
Closing this, as it's expected behavior. @sompylasar Feel free to reopen if you still have issues.

**Closed by lbogdan** 2019-03-28 16:14 UTC
