### ISSUE TITLE
Jest testing issue in Firefox

### ISSUE THREAD

**Issue by AWolf81** [CompuIves/codesandbox-client#540] opened 2018-02-11 23:29 UTC
The following [example](https://codesandbox.io/s/4lwz2mw4px) doesn't start properly in Firefox  58.0.2 (64-Bit) Windows 10.

I'm getting multiple errors in the console that I'm not able to fix and displaying of the test panel is taking really long 5-10 seconds.

After a click on the play button in the test panel I'm getting errors like in the following screenshot:
![Error](https://user-images.githubusercontent.com/3046542/36080009-f516a814-0f89-11e8-9298-f273a573144d.png)

The messages are all about `Unhandled promise rejection` but for different methods:
- evaluate@src/setupTests.js (logged 4 times)
- _inherits@https://4lwz2mw4px.codesandbox.io/node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:43:113 (logged twice)
- evaluate@src/setupTests.js (last log message)

Maybe this is just a loading/caching issue because I've seen the test reporting correctly in Firefox (see screenshot below) but I don't know how I got it to work (code of sandbox unchanged).
![Working output](https://user-images.githubusercontent.com/3046542/36080027-3b498658-0f8a-11e8-8700-4487e04c6866.png)

**Comment by gautamarora** [comment] 2018-02-13 12:03
@AWolf81 - I am getting the same errors for your sandbox and [even a simpler one that was working earlier](https://codesandbox.io/s/009pr18q10) on Chrome. It appears when I start a sandbox in chrome incognito mode, it works fine but then on second load I get the same error as you are reporting.

Also, the dev tools panel is certainly taking a long time to load but its way quicker for a sandbox with tests that doenst use `setupTests` e.g. [redux todomvc](https://codesandbox.io/s/github/reactjs/redux/tree/master/examples/todomvc)

As I was trying to dig into the issue and eliminate other causes, [i forked your sandbox](https://codesandbox.io/s/0ox4k14yvw) that adds `babel-core` and removes `chai` & `sinon` replacing it with jest's `expect` and `jest.fn` but that too gets the same error on second load.

**Comment by gautamarora** [comment] 2018-02-13 12:19
actually, the speed of testing doesnt seem to be an issue in the examples, when run for the first time in incognito window, the test run is completed in ~50ms.

![image](https://user-images.githubusercontent.com/1215971/36149519-064d86d6-10e6-11e8-81cc-5a48f0665a77.png)

cc @CompuIves for ideas on how we can debug this further.

**Comment by CompuIves** [comment] 2018-02-13 12:45
Hm, this could be related to our caching mechanism.

It can maybe be solved if we add the `isEntry` value to the cache save/load here:

https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/eval/transpiled-module.js#L814

and here:

https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/sandbox/eval/transpiled-module.js#L778

I cannot reproduce the error of the sandbox mentioned earlier though, do you need to do a page reload or a sandbox reload?

**Comment by gautamarora** [comment] 2018-03-01 21:49
@CompuIves - i tested the sandboxes reported above, and am seeing the same issue. Tests run successfully on first page load, on second page load the test view doesn't complete the test run.

Affected sandboxes:
React-TDD Example by @AWolf81 - https://codesandbox.io/s/4lwz2mw4px
React-TDD Example by me (forked from the above one and replaces chai/sinon with jest): https://codesandbox.io/s/0ox4k14yvw
Simple Enzyme test that uses `setupTests.js` - https://codesandbox.io/s/009pr18q10

This is what all of them show on second page load, i am seeing it in firefox and sometimes in chrome too: 
![image](https://user-images.githubusercontent.com/1215971/36871446-49f45f90-1d70-11e8-8c29-091a32b1bfef.png)

The Redux TodoMVC sandbox doesnt seem to be having this issue on second page load.

**Comment by lbogdan** [comment] 2018-05-03 01:07
@AWolf81 , @gautamarora Are you guys still seeing this? I can't seem to reproduce it here.

**Comment by AWolf81** [comment] 2018-05-03 22:11
@Ibogdan I re-tested my sandbox and the other mentioned sandboxes. But I also can't reproduce the behaviour in FF 59.0.3.  Test panel opens immediately and shows the results. 

No error messages in the console anymore.

**Comment by lbogdan** [comment] 2018-05-04 12:34
Ok, I'll close this for now. If you come across any related issues, please re-open.

**Closed by lbogdan** 2018-05-04 12:34 UTC
