### ISSUE TITLE
Frenzied cubes

### ISSUE THREAD

**Issue by Komar0ff** [CompuIves/codesandbox-client#799] opened 2018-05-05 21:51 UTC
**Switched to another tab, and then went back and saw it:**

![image](https://user-images.githubusercontent.com/10588170/39667759-b191c24a-50c5-11e8-97da-a59d972c733e.png)
**Until I understood how to fix**

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | -
| Browser | Chrome/66.0.3359.139
| Operating System | Linux/4.15.15-1-ARCH

**Comment by CompuIves** [comment] 2018-05-09 09:37
Ah yes, this one haha. This one should be fixed one day, but is on the low prio list for me currently 😄.

**Comment by lbogdan** [comment] 2018-05-10 15:48
Closing this as duplicate of #452 .

**Closed by lbogdan** 2018-05-10 15:48 UTC
Labels: bug
