### ISSUE TITLE
User Menu is missing after deleting the current Sandbox

### ISSUE THREAD

**Issue by ReneCode** [CompuIves/codesandbox-client#669] opened 2018-03-26 19:15 UTC
- open a sandbox from "my sandboxes"
- in "project info" click "delete sandbox"
- => a new blank (react) sandbox apears
- => the User Menu (top right corner) is missing when clicking on the user-avatar. (only the hint apears)

**Comment by CompuIves** [comment] 2018-03-27 10:59
Very interesting, thanks for sending the bug report!

This is probably because there is an inconsistency in the Cerebral state.

**Comment by steventsao** [comment] 2018-06-13 01:37
I have not been able to reproduce this issue. See attempt https://youtu.be/BIJrf0b9dtw

**Comment by CompuIves** [comment] 2019-04-03 12:42
Thanks for the reproduction @steventsao! I think we can close this one.

**Closed by CompuIves** 2019-04-03 12:42 UTC
Labels: bug, help wanted
