### ISSUE TITLE
Intermittent Raven JS error prevents saves

### ISSUE THREAD

**Issue by iamtmrobinson** [CompuIves/codesandbox-client#986] opened 2018-07-19 12:44 UTC
# 🐛 bug report

## Description of the problem

Periodically I'll be editing something in the sandbox and I receive the following error when I try to save:

```
raven.js:422 Uncaught Error: The operation's base length must be equal to the string's length.

Error: The operation's base length must be equal to the string's length.
    at e.apply (common.bdbdee4f.chunk.js:1)
    at t.r.sendChangeOperations (app.d2918860.js:1)
    at app.d2918860.js:1
    at e.fire (event.ts:543)
    at diffEditorWidget.ts:126
    at textModel.ts:1580
    at e.fire (event.ts:543)
    at t.endDeferredEmit (cursorTypeOperations.ts:150)
    at f.pushEditOperations (textModel.ts:2584)
    at Function.e._innerExecuteCommands (splitLinesCollection.ts:354)
    at Function.e.executeCommands (splitLinesCollection.ts:297)
    at t._executeEditOperation (runtimeMinimapCharRenderer.ts:984)
    at t._type (splitLinesCollection.ts:220)
    at t.trigger (splitLinesCollection.ts:135)
    at t.trigger (diffReview.ts:447)
    at t.runCommand (coreCommands.ts:1598)
    at handler (suggestMemory.ts:176)
    at e.invokeFunction (instantiationService.ts:120)
    at e.executeCommand (fake:1)
    at Object.type (diffEditorWidget.ts:279)
    at e.type (coreCommands.ts:1641)
    at textAreaHandler.ts:514
    at e.fire (event.ts:543)
    at HTMLTextAreaElement.<anonymous> (intervalTree.ts:1001)
    at HTMLTextAreaElement.d (raven.js:418)
    at e.apply (common.bdbdee4f.chunk.js:1)
    at t.r.sendChangeOperations (app.d2918860.js:1)
    at app.d2918860.js:1
    at e.fire (event.ts:543)
    at diffEditorWidget.ts:126
    at textModel.ts:1580
    at e.fire (event.ts:543)
    at t.endDeferredEmit (cursorTypeOperations.ts:150)
    at f.pushEditOperations (textModel.ts:2584)
    at Function.e._innerExecuteCommands (splitLinesCollection.ts:354)
    at Function.e.executeCommands (splitLinesCollection.ts:297)
    at t._executeEditOperation (runtimeMinimapCharRenderer.ts:984)
    at t._type (splitLinesCollection.ts:220)
    at t.trigger (splitLinesCollection.ts:135)
    at t.trigger (diffReview.ts:447)
    at t.runCommand (coreCommands.ts:1598)
    at handler (suggestMemory.ts:176)
    at e.invokeFunction (instantiationService.ts:120)
    at e.executeCommand (fake:1)
    at Object.type (diffEditorWidget.ts:279)
    at e.type (coreCommands.ts:1641)
    at textAreaHandler.ts:514
    at e.fire (event.ts:543)
    at HTMLTextAreaElement.<anonymous> (intervalTree.ts:1001)
    at HTMLTextAreaElement.d (raven.js:418)
    at event.ts:206
    at d (raven.js:418)
```

I'm able to continue editing and updates take effect but they are not saved.

I have to copy my current code, close the editor, re-open the editor and paste my code back in, at which point everything works fine again. Sometimes even this doesn't work and I have to close codesandbox completely and reload for it to work again.

## How has this issue affected you? What are you trying to accomplish?

I was just editing code as normal - I've tried it in several of my sandboxes with the same result. They are all vanilla sandboxes with dependencies on `d3`, `shortid` and `random-js`.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  |
| Browser | Chrome Version 67.0.3396.99 (Official Build) (64-bit) |
| Operating System | Mac OSX Sierra 10.12.6 |

**Comment by CompuIves** [comment] 2018-07-22 01:38
Hey! I deployed two updates this week that should fix your issue. I'm not able to reproduce the problem here locally anymore. If you the issue happens to pop up again, please let me know 😄. This one is high priority to fix if it happens.

I'll close this one now, will reopen if the issue hasn't been completely fixed!

**Closed by CompuIves** 2018-07-22 01:38 UTC

**Comment by iamtmrobinson** [comment] 2018-07-23 07:47
Thanks a lot @CompuIves - I'll update if I see it again 👍

**Comment by danielzabotti** [comment] 2019-05-23 05:36
The bug is back

```
vendors~app.65e0638b.chunk.js:14 Error: The operation's base length must be equal to the string's length.
    at e.apply (common.288a2fdf.chunk.js:168)
    at c (default~app~embed.024f3854.chunk.js:276)
    at n.sendChangeOperations (default~app~embed.024f3854.chunk.js:276)
    at default~app~embed.024f3854.chunk.js:276
    at codesandbox.editor.main.js:1
    at e.fire (codesandbox.editor.main.js:1)
    at t.endDeferredEmit (codesandbox.editor.main.js:1)
    at r.pushEditOperations (codesandbox.editor.main.js:1)
    at Function.e._innerExecuteCommands (codesandbox.editor.main.js:1)
    at Function.e.executeCommands (codesandbox.editor.main.js:1)
    at t._executeEditOperation (codesandbox.editor.main.js:1)
    at t._paste (codesandbox.editor.main.js:1)
    at t.trigger (codesandbox.editor.main.js:1)
    at t.trigger (codesandbox.editor.main.js:1)
    at t.runCommand (codesandbox.editor.main.js:1)
    at handler (codesandbox.editor.main.js:1)
    at e.invokeFunction (codesandbox.editor.main.js:1)
    at Proxy.t._tryExecuteCommand (codesandbox.editor.main.js:1)
    at codesandbox.editor.main.js:1
```
