### ISSUE TITLE
feature: add link from homepage to login

### ISSUE THREAD

**Issue by ferdaber** [CompuIves/codesandbox-client#654] opened 2018-03-20 12:30 UTC
I often go to the codesandbox home page directly via the URL (codesandbox.io), it looks like when I'm already logged in, I will see a link to my user page on the top right corner, but when I'm not logged in, there isn't any link at all. It'd be nice for me to be able to log in to my user profile via the home page.

Currently the workflow is that I have to go into one of the template pages and log in through there.

**Comment by lbogdan** [comment] 2018-10-22 16:08
Closed as duplicate of #334 .

**Closed by lbogdan** 2018-10-22 16:08 UTC
