### ISSUE TITLE
Update all dependencies?

### ISSUE THREAD

**Issue by johncokos** [CompuIves/codesandbox-client#1333] opened 2018-11-27 04:33 UTC
# 🌈 Feature

Today, we can update any single dependency to the latest version available through the link next to the package. Would be nice if we could do them all at once ... Can you add a hot-link in the dependencies drop-down that would update all dependencies to the latest versions

Execute an ncu update or whatever you're using to let us update each dependency individually right now.

**Comment by SaraVieira** [comment] 2019-02-18 14:56
Closed as duplicate of https://github.com/CompuIves/codesandbox-client/issues/1333

**Closed by SaraVieira** 2019-02-18 14:56 UTC

**Comment by tinymachine** [comment] 2019-06-11 22:31
> Closed as duplicate of #1333

@SaraVieira This issue actually is #1333; could you update with the correct duplicated issue number? Thanks!
