### ISSUE TITLE
Improve PWA icon contrast

### ISSUE THREAD

**Issue by jgierer12** [CompuIves/codesandbox-client#1198] opened 2018-10-16 21:10 UTC
# 🌈 Feature

First off, I was very happy to discover that CodeSandbox already supports Chrome 70's desktop PWA installation feature! This means that I can now run it like any other Windows program. However, I noticed that the app icon is almost indistinguishable from Windows 10's black taskbar:

![Current icon](https://user-images.githubusercontent.com/4331946/47047217-44d6e100-d197-11e8-9db2-21eb3ddabf99.png)

This can be fixed by creating a higher-contrast icon and linking it in the `manifest.json`. To be clear, this would change only the taskbar icon; the website's favicon would stay unaffected.

Perhaps an improved icon could look something like this, with a solid light background:

![Improved icon](https://user-images.githubusercontent.com/4331946/47047555-2a513780-d198-11e8-8f3b-45fdc3443259.png)

**Comment by lbogdan** [comment] 2019-03-26 23:10
Closing as duplicate of #1644 .

**Closed by lbogdan** 2019-03-26 23:10 UTC
