### ISSUE TITLE
Broken transpiler

### ISSUE THREAD

**Issue by artalar** [CompuIves/codesandbox-client#662] opened 2018-03-24 06:50 UTC
PROD-1521819790
Yandex Browser 18.1.1.952 beta (64-bit) (same as the Chrome)

I'm creating the new extended class, but methods not apply:
![image](https://user-images.githubusercontent.com/27290320/37861311-3cafa01c-2f48-11e8-91f1-75d3cda495ea.png)

In the browser  console all right:
![image](https://user-images.githubusercontent.com/27290320/37861339-affed86c-2f48-11e8-9127-830ce5ce5467.png)

**Comment by CompuIves** [comment] 2018-04-07 12:00
Interesting, I think this is an issue with the Babel transpiler. I reproduced it here: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYGwhgzhAEAqCmEAu14A8nwHYBMYEEAnQsAT2gG8AoaABwFcIALACgEpKbppD4l7CWaAHJMyYQG4aAXyqyqwAPZYIikPAB0IRQHMWLLPADucREhYBtALps2GhsxYBGW0A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=.

I think we should close this one since it's out of scope for CodeSandbox. What you could do is something like this:

https://codesandbox.io/s/j48y21knl3

In this sandbox I disabled all transforms by Babel.

**Closed by CompuIves** 2018-04-07 12:00 UTC
