### ISSUE TITLE
Spacing is off slightly

### ISSUE THREAD

**Issue by kentcdodds** [CompuIves/codesandbox-client#1012] opened 2018-07-27 16:04 UTC
# 🐛 bug report

## Description of the problem

The spacing is slightly off from the spacing lines.

![kapture 2018-07-27 at 10 02 43](https://user-images.githubusercontent.com/1500684/43332044-60109e6e-9184-11e8-9b3e-29126f52d861.gif)

## How has this issue affected you? What are you trying to accomplish?

It's kinda annoying 😅 

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1532378173-dcdb416
| Browser | Chrome 68
| Operating System | macOS 10.12.6

**Comment by lbogdan** [comment] 2019-03-28 17:30
Closing this as duplicate of #1595 , please follow that instead.

**Closed by lbogdan** 2019-03-28 17:30 UTC
