### ISSUE TITLE
I can't open one of my sandboxes because of Maximum call stack size exceeded

### ISSUE THREAD

**Issue by YazanAabeed** [CompuIves/codesandbox-client#838] opened 2018-05-15 15:19 UTC
# 🐛 bug report

## Description of the problem
When I do something wrong that makes a recursion calls the site stop working without any response. 

## How has this issue affected you? What are you trying to accomplish?
It not really affected me, but every time I do something wrong I need to force quit my chrome to continue working with code sandbox.

Is there is a way with vanilla JavaScript to handle if calls more than the limited to stop or give a warning that nothing will be executed?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |
| Browser Chrome | Version 68.0.34 |
| Operating System | MacOS |

**Comment by lbogdan** [comment] 2019-03-28 16:44
Closing this, as I can't reproduce in the provided sandbox. We have some loop protection in place, but sometimes it's just impossible to prevent this kind of thing.

**Closed by lbogdan** 2019-03-28 16:44 UTC

**Comment by MichaelLeeHobbs** [comment] 2019-07-03 20:18
I add this to all my projects now to avoid this

```
const recursionGuard = (max = 1000) => {
  if (typeof window.__recursions === "undefined") window.__recursions = 0;
  window.__recursions++;
  if (window.__recursions > max) {
    let errorMsg = `Recursion guard! recursions(${
      window.__recursions
    }) > max(${max}) allowed!`;
    console.error(errorMsg);
    throw new Error(errorMsg);
  }
};

module.exports = recursionGuard;

// In the code I'd have something like this


import React from "react";
import ReactDOM from "react-dom";
import recursionGuard from "./recursionGuard";

import "./styles.css";

var loops = 0;
const rtest = () => {
  loops++;
  recursionGuard();
  console.log(loops);
  setImmediate(() => rtest());
};
rtest();
```

If the guard throws an error you have to hit the browser refresh button to clear it. I'm sure there is a way to add this to all user-defined functions using metaprogramming or perhaps something like babel but that might be more work than it's worth.
