### ISSUE TITLE
Change default command or kill default process

### ISSUE THREAD

**Issue by manniL** [CompuIves/codesandbox-client#1295] opened 2018-11-11 18:26 UTC
# 🌈 Feature

I'd be awesome for SSE sandboxes to change the default command and kill the process that one runs in. In my case, I can't deploy a production version of Nuxt in the sandbox otherwise.

**Comment by SaraVieira** [comment] 2018-11-24 13:00
Hey!

Can you explain this better pls ?

**Comment by manniL** [comment] 2018-11-24 13:09
@SaraVieira Sure!

Say you fork the [official Nuxt template CSB](https://codesandbox.io/s/github/nuxt/codesandbox-nuxt/). Then you always have the default command running in the Terminal section

![image](https://user-images.githubusercontent.com/640208/48968608-e567be80-efe9-11e8-9513-a6efe6232ed9.png)

If you open new terminal windows, you can kill them with the :x: button but you cannot kill the default terminal/command running (no :x: button).

This is a problem when I want to deploy a production version of Nuxt in such a Codesandbox as I'd have to use `nuxt build && nuxt start`. The default command is using just `nuxt` though.

**Comment by SaraVieira** [comment] 2018-11-24 13:14
OH! Makes sense, it would be a cool enhancement!

Maybe a kill serverr button here:

![screenshot 2018-11-24 at 14 13 43](https://user-images.githubusercontent.com/1051509/48968685-36c87b80-eff3-11e8-947c-ea6e41a35260.png)

**Comment by lbogdan** [comment] 2018-11-24 15:57
Actually, not really. This is by design, we assume there is a "main process" running at all times. We try to run `dev`, `develop`, `serve`, `start` scripts defined in `package.json`, in this specific order. So if you want to start `nuxt build && nuxt start`, define that as your `dev` script (or remove the `dev` script and define it as the `start` script).

**Comment by manniL** [comment] 2018-11-24 16:10
@lbogdan Okay that makes sense! I thought that'd be based on the used `template` instead (and not based on the `package.json`). 

I still think that bit of freedom would be nice to have (but it's not as important with that new peace of info)

**Comment by lbogdan** [comment] 2018-11-24 16:19
That assumption was mainly because if there's nothing running, there would be nothing to preview, either, and we wanted users to have pretty much the same experience on client and server sandboxes.

Closing this, as I hope that answered your issue.

**Closed by lbogdan** 2018-11-24 16:19 UTC
Labels: SSE
