### ISSUE TITLE
text selection clipboard issues under ubuntu

### ISSUE THREAD

**Issue by eps1lon** [CompuIves/codesandbox-client#1656] opened 2019-03-26 08:26 UTC
# 🐛 bug report

## Description of the problem
Selecting a text and pasting text from the clipboard does not replace the selection but moves the cursor to the end of the selection.
![codesandbox-clipboard](https://user-images.githubusercontent.com/12292047/54981586-f4b34480-4fa8-11e9-947c-a6e332e5a2b3.gif)

## How has this issue affected you? What are you trying to accomplish?
Basic text editing

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553261537-e53862f6e
| Browser | Chrome Version 73.0.3683.75 (Official Build) (64-bit)
| Operating System | Ubuntu 18.04.2 LTS

**Comment by lbogdan** [comment] 2019-03-26 08:54
That's very weird behavior, indeed, unfortunately I can't replicate it here, on either Windows or macOS.

**Comment by eps1lon** [comment] 2019-03-26 09:11
Indeed. If I use a windows machine through browserstack.com it is working.

**Comment by doasync** [comment] 2019-03-26 14:38
When you select any text it is automatically copied to clipboard. It a very annoying bug 🕷

Environment:
Chrome Version 73.0.3683.86 (64-bit)
Ubuntu 18.04.2 LTS

**Comment by doasync** [comment] 2019-03-26 14:41
@eps1lon, I suggest you to rename the issue to something like "Autocopying text on selection"

**Comment by eps1lon** [comment] 2019-03-26 14:47
> @eps1lon, I suggest you to rename the issue to something like "Autocopying text on selection"

But this is not my original issue. Maybe it's related, maybe not.

**Comment by AniaMakes** [comment] 2019-03-28 14:12
@doasync I have the same issue (any text selected is automatically copied to the clipboard)

Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Ubuntu 16.04 LTS

**Comment by lbogdan** [comment] 2019-03-28 15:30
@CompuIves I guess you'll have to install Ubuntu on your MacBook? 😃

**Comment by eps1lon** [comment] 2019-03-28 15:56
I could take a look as well. I just don't have any idea where to start.

**Comment by lbogdan** [comment] 2019-03-28 16:19
It's probably something deep inside the VSCode internals, so I have no idea, either. @CompuIves , can you please advise?

**Comment by lbogdan** [comment] 2019-03-28 16:23
@eps1lon You could start by reading the [contributing guide](https://github.com/CompuIves/codesandbox-client/blob/master/CONTRIBUTING.md) and making CodeSandbox work locally, if you haven't already.

**Comment by eps1lon** [comment] 2019-03-28 16:53
Sure did. I already came in contact with the vscode-editor files in #1625. I'm not sure where those come from or what the difference between vscode and monaco is. I couldn only find a repo to the monaco editor and I have no clipboard issues in that playground.

**Comment by CompuIves** [comment] 2019-04-01 14:44
I found the cause of the issue! It was caused by some Linux clipboard override by VSCode, but this doesn't really work in the browser. Line is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/codeEditor/browser/selectionClipboard.ts#L95.

I changed this line:
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/codeEditor/browser/selectionClipboard.ts#L26

to

`if (platform.isLinux && !platform.isWeb)`

to fix it.

> I couldn only find a repo

I realized that only my local clone of the repo has the `vscode` repo with it. I'll make it possible for everyone to look into it.

This fix will be live in a couple hours. Sorry for this inconvenience!

**Comment by eps1lon** [comment] 2019-04-01 17:46
> This fix will be live in a couple hours. Sorry for this inconvenience!

Glad to hear, thanks. Really enjoyed the v3 release so far. Big :+1:  to the whole team.

**Comment by AniaMakes** [comment] 2019-04-02 08:25
Thank you for prompt action on this!

**Comment by CompuIves** [comment] 2019-04-02 09:18
Fix is live! Let me know if it worked 😄.

You might have to refresh twice to see the update (service worker), the version is `bfa0322` which you can see in the bottom left.

**Comment by eps1lon** [comment] 2019-04-02 09:50
Works like a charm. Thanks!

**Comment by CompuIves** [comment] 2019-04-02 11:35
Niiiiice! Closing this one then 😄

**Closed by CompuIves** 2019-04-02 11:35 UTC
Labels: ASAP, VSCode, bug?
