### ISSUE TITLE
After I got out of your profile, then I need to refresh the page to return to the main menu

### ISSUE THREAD

**Issue by yakotika** [CompuIves/codesandbox-client#852] opened 2018-05-22 18:03 UTC
# 🐛 bug report

## Description of the problem
After I got out of your profile, then I need to refresh the page to return to the main menu. Otherwise I just have a black screen

**Comment by arthurdenner** [comment] 2018-06-06 02:45
Hey @yakotika, could you please provide more information about this issue? Sorry about this, but I didn't get what you mean with "got out of your profile", therefore, I couldn't reproduce what you described. I visited a few profiles, clicked here and there, but never got stuck in a black screen.

PS: If this is not happening anymore, could you please close the issue?

**Comment by yakotika** [comment] 2018-06-06 17:36
@arthurdenner 
![jun-06-2018 20-30-16-min](https://user-images.githubusercontent.com/22033385/41055206-44d8e81e-69c9-11e8-8e24-f90c575a8121.gif)

**Comment by arthurdenner** [comment] 2018-06-06 18:00
Thank you very much for the GIF, @yakotika, very helpful! I'll try to fix this as soon as I can.

**Closed** 2018-06-08 09:47 UTC
