### ISSUE TITLE
Improve keybinding

### ISSUE THREAD

**Issue by gnumaniac** [CompuIves/codesandbox-client#456] opened 2018-01-16 13:56 UTC
Using a bluetooth keyboard on ios platform, the arrows key does not work.
According to the keybinding settings section, events from a key press are "uikeyinputR/L/U/D" rather than ArrowUP/DOWN/LEFT/RIGHT.

**Comment by lbogdan** [comment] 2018-05-02 23:25
Closing as duplicate of #507 .

**Closed** 2018-05-10 14:41 UTC
