### ISSUE TITLE
Newest update overrides documents on save

### ISSUE THREAD

**Issue by Agustin-JV** [CompuIves/codesandbox-client#1343] opened 2018-11-30 22:28 UTC
# 🐛 bug report

## Description of the problem
The current open file will override another file of the open tab, replacing its content with the other when using the save button.
*-not entirely sure if is the current open file to another file or the other way around-*

One of the latest updates should have created it, probably one from  29 of November.

## How has this issue affected you?
It essentially destroys one file if not backed up by with git.

Example:

 Open file | |Other file that is also open but not visible 
------------ |--- |-------------
componentX.js | | index.js 
... | | ...
`class ComponentX extends Component {... ` | => | `class ComponentX extends Component {...`

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
**Browser** 
Chrome | 70.0.3538.110
**Operating System** 
Windows | 10 Enterprise

**Comment by CompuIves** [comment] 2018-12-01 14:08
Hey! I believe I fixed this recently, so I need to make sure which version you're getting this issue with.

Do you have VSCode enabled? And which version of CodeSandbox are you running? (You can find the latter in the bottom left corner of the editor).

**Comment by Agustin-JV** [comment] 2018-12-03 15:32
Hello,
A bit more detail on my end and also a friend that had the same issue, we are running some what slow computers that sometimes lags when changing tabs in chrome, and when the bug occurs also happens that while using the save button it stalls for a bit, it may only happen to us and anyone running a slow machine that is mono-task and usually happens when we are close to ending our codding session, when we have multiple tabs open, and we start to save and close all our work, and our machines are running their slowest by then.

I'm running 

Software | Version
--|--
CodeSandbox | PROD-1543715511-2cf33c46 
VSCode| Enabled

Additional Machine info:

Component | Spec
--|--
Processor| Intel i3-4130T 2.9GHz
RAM| 4GB

**Comment by camflan** [comment] 2018-12-06 15:02
I had this happen to me and lost the contents of a few large files 😬. I was able to rebuild them manually, but now I'm very worried about something that has always been bulletproof.

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1543948045-b1c31dd0 |
| Browser | Chrome 70.0.3538.110 (Official Build) (64-bit) |
| Operating System | Mac OS 10.14.1 |

**Comment by CompuIves** [comment] 2018-12-06 20:46
I think I fixed it with this commit; https://github.com/CompuIves/codesandbox-client/commit/954eac626819ba1a3b26c514aad3b63997a89796.

It's pretty  hard to test because I can't seem to reproduce the bug 😅. Hopefully this one will fix it.

**Comment by lbogdan** [comment] 2019-03-26 20:28
Closing this, as there were no more comments since the fix. Feel free to reopen if it's still happening, though.

**Closed by lbogdan** 2019-03-26 20:28 UTC
