### ISSUE TITLE
Hyperapp Support

### ISSUE THREAD

**Issue by artyprog** [CompuIves/codesandbox-client#625] opened 2018-03-05 15:21 UTC
Hy,

Thank you very much for CodeSandbox.

Regards

**Comment by tomkuehl** [comment] 2018-03-06 14:22
there already exists an issue for hyperapp support: https://github.com/CompuIves/codesandbox-client/issues/480

**Comment by lbogdan** [comment] 2018-05-02 23:53
Closing this as duplicate of #480 .

**Closed by lbogdan** 2018-05-02 23:53 UTC
