### ISSUE TITLE
Set interval affects on random numbers

### ISSUE THREAD

**Issue by mrGrochowski** [CompuIves/codesandbox-client#1412] opened 2018-12-28 14:27 UTC
# 🐛 bug report

![](https://media.giphy.com/media/9r75fIKnT23Di3tYJa/giphy.gif)

Using random (no matter Mat.random(0 or 3part lib I got takt issue. Better than that, sandbox cache something and when I attouch pure string, sometimes I recive Int o.0

I heppends inside Interval loop

Link to sandbox: https://codesandbox.io/s/x9j10ov9lw
### Your Environment 
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Latest chrome Version 71.0.3578.98 (official) (64-bitowa)
| Operating System | Win 10

**Comment by mrGrochowski** [comment] 2018-12-28 14:31
![k98evonh4y](https://user-images.githubusercontent.com/25830868/50518365-949a2880-0ab5-11e9-96c3-ea2c384b0816.gif)

**Comment by lbogdan** [comment] 2018-12-28 16:42
Hey @mrGrochowski , I didn't quite understand what the issue is. Can you please describe what are you expecting vs. what's actually happening?

**Comment by mrGrochowski** [comment] 2018-12-31 13:55
1. Use setInterval 
2. Console log something from interval
3. Change console log for something diffrent
4. Then Codesandbox cached both console logs and randomly log as You see above.

What I need?
Don't need to reload whole page and using live reload properly without this bug.

**Comment by lbogdan** [comment] 2018-12-31 13:59
You need to clear the interval in the `beforeDestroy` lifecycle hook, otherwise it will just continue to run until you refresh the page.

**Comment by lbogdan** [comment] 2019-03-26 09:40
Closing this, as it's expected behavior. Please reopen if you have further issues.

**Closed by lbogdan** 2019-03-26 09:40 UTC
